version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: loja-postgres
    environment:
      POSTGRES_DB: loja_virtual
      POSTGRES_USER: loja
      POSTGRES_PASSWORD: loja123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
